### ISSUE TITLE
Support async

### ISSUE THREAD

**Issue by hdoordt** [eldruin/lsm303agr-rs#30]
Hi @eldruin thanks for another great driver crate!

I'm looking to use this driver in an async context. Would you be in favour of adding driver implementations based on `embedded-hal-async` traits? If so, what would you suggest be the best way to go about it?

**Comment by eldruin** [comment]
Hi, you are welcome.
I would indeed be interested in adding async support here.
At the moment the best approach I have seen is using `maybe-async-cfg`.
You can probably draw a lot of inspiration from https://github.com/eldruin/pwm-pca9685-rs/pull/16 .

**Comment by hdoordt** [comment]
Sounds good! I'll have a stab at it and open a PR once I'm happy
