### ISSUE TITLE
`mag_status()` breaks down when future is dropped

### ISSUE THREAD

**Issue by cyril-marpaud** [eldruin/lsm303agr-rs#34]
Hello !

I've been playing a bit with this (awesome, thank you for your efforts !) crate & noticed that dropping the future returned by `mag_status()` results in impossibility to make new measurements.

I was trying to count how many mag measures can be made each second on microbit with embassy. Here are two versions of the code:

- working: https://github.com/cyril-marpaud/embassy_lsm303agr/blob/WORKING/src/main.rs
  counting happens in the display task
- broken: https://github.com/cyril-marpaud/embassy_lsm303agr/blob/BROKEN/src/main.rs
  counting happens in the measure task
  the `select` line 65 drops the future that resolves last. It provokes I2c-bus errors that can't seem to be recovered from

I thought reporting that might be of interest to you. Am I doing anything wrong ? Is there a manual somewhere that I forgot to read ?

Thanks again for the crate !

**Comment by eldruin** [comment]
Hi, you are welcome.
I suggest you talk to the embassy guys about this. Here is the [chat room](https://matrix.to/#/#embassy-rs:matrix.org), the [book](https://embassy.dev/book/) and the [repository](https://github.com/embassy-rs/embassy).
Please feel free to reopen this if needed.
